### ISSUE TITLE
მთავარ გვერდზე "ყველა დეველოპერის" ნაწილი დიზაინში მხოლოდ ტექსტია, ფრონტში გარშემო ბორდერი აქვს. ასე შეთანხმდით საბოლოოდ შენ და სალომე?

### ISSUE THREAD

**Issue by AnanoAspanidze** [GeoLabJuniors/Sxva-Saqartvelo-Front-End#2]

**Comment by gsanikidze** [comment]
როგორც მარხსოვს, ღილაკს რომ დამსგავსებოდა უფრო მაგიტო გავაკეთე. სალომეს ვკითხე, ისე არაფერი შემიცვლია.

**Comment by AnanoAspanidze** [comment]
კარგი. 
ლამაზია, მე მომწონს.
ერთი, წარწერის გვერდით რაღაც აიქონი რომაა, ის არ ჩანს.

http://othergeorgia.geolab.edu.ge/

ოთხკუთხედი (ტოფუ) ჩანს.

![image](https://user-images.githubusercontent.com/17623524/32508081-9a9bb99c-c402-11e7-8e6a-b15c31e3a1e2.png)

**Comment by gsanikidze** [comment]
![image](https://user-images.githubusercontent.com/15326244/32510762-12e9f5be-c40b-11e7-8a3f-e33ca8b2dc36.png)
ჩემთან იკონკაა. რა პონტია არ ვიცი, გადავხედავ მერე

**Comment by gsanikidze** [comment]
ჩემთან ჩვეულებრივად ჩანს, და ვერ ვიგებ ამიტო დავაკომენტარე ეგ ნაწილი და აღარ გამოჩნდება საერთოდ იკონკა
