### ISSUE TITLE
მთავარი გვერდის მენიუ

### ISSUE THREAD

**Issue by AnanoAspanidze** [GeoLabJuniors/Sxva-Saqartvelo-Front-End#3]
მთავარი გვერდის მენიუ დიზაინში სხვანაირად იყო, ახლა ბურგერ მენიუშია გატანილი. ამ მენიუში რა ხდება, რომ ჩამოიშლება, ეს დაამატე, რა.

**Comment by gsanikidze** [comment]
მთავარ გვერდზე ეგ მაქ მარტო დარჩენილი და დავამატებ
