### ISSUE TITLE
კანდიდატების გვერდის მცირე ცვლილებები

### ISSUE THREAD

**Issue by AnanoAspanidze** [GeoLabJuniors/Sxva-Saqartvelo-Front-End#5]
ყველაფერი არის იდეალური. ორი პატარა შეკითხა მაქვს:
1. წავშალე. არ გვინდა.
2. გასუფთავსების ღილაკი რომ აამუშავო - რომ დააჭერს, ყველა მოპწიჩკული მოიშალოს და რეიტინგი ისევ 0-დან 100-მდე რომ ჩაიწეროს.
3. შესაძლებლობების და რეიტინგის სექციებს ჩამოშლა და აშლა რომ აქვთ, მაგაზე ჰოვერზე pointer გაუკეთე, რა მაუსს. და ჩაშლა-ამოშლა მარტო წარწერებზე კლიკის დროს კიარა, ისარზე კლიკის დროსაც რომ იყოს.
4. წავშალე. არ გვინდა.
5. კანდიდატების გვერდიდან ლოგოს რომ დავაჭერ, ინდექს გვერდზე გადამიყვანოს.

**Comment by gsanikidze** [comment]
1. სალომესაც თუ ვკითხავთ კაი იქნება, მარა მე პირადად ეგრევე რო იფილტრება მომწონს, კომფორტულია.
4. უბრალოდ გავაწითლო ღილაკები, თუ სხვა კონტენტი ჩავტვირთო?

**Comment by AnanoAspanidze** [comment]
1. იყოს მოდი ეს და მერე თუ მოუნდებათ შეცვლა, შევცვალოთ.
2. ამას რომელზე მეკითხები? 


გასუფთავსების ღილაკი რომ აამუშავო - რომ დააჭერს, ყველა მოპწიჩკული მოიშალოს და რეიტინგი ისევ 0-დან 100-მდე რომ ჩაიწეროს.
- აქ ვიგულისხმე, რომ რამეებს რომ მოვპწიჩკავ ან რეიტინგში 0-ის და 100-ის მაგივრად სხვა რიცხვებს ჩავწერ, მერე შეიძლება, მომინდეს ამ ფილტრის გაწმენდა და "გასუფთავების" ღილაკს რომ დავაჭერ, ყველა მოპწიჩკული გაქრეს (შესაძლებლობებში) და რეიტინგში ისევ 0-დან 100-მდე ჩაეწეროს.


4. შესაძლებლობებში წერტილები რომ არის ქვემოთ (თუ ბევრი იქნება, ფეინჯინგივით რომ აქვს), ამათშიც ჩაყარე რამე, რომ ამ ნაწილმაც იმუშაოს, რა. - ამას დაანებე თავი. ეს მერე ვქნათ.

ახლა გააკეთე მე-2, მე-3 და მე-5. დანარჩენს წავშლი.

**Comment by gsanikidze** [comment]
კარგი ანანო, გასაგებია
